version: '3.8'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskflow
      - JWT_SECRET=taskflow_super_secret_jwt_key_2024
      - JWT_EXPIRE=7d
      - NODE_ENV=production
      - CLIENT_URL=http://localhost
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
